 version: '1'
 image: golang:latest
 jobs:
   check:
     when:
       branch:
         exclude:
           - master
     script:
       - make check
     allowFailure: true

   test:
     script:
       - make test
   
   submit-cov:
     env:
       CODECOV_TOKEN: {{CODECOV_TOKEN}}
     script:
       - bash <(curl -s https://codecov.io/bash)

   build:
     script:
       - make build
     dependencies:
       - test

   release:
     when:
       branch:
         - master
     script:
       - make publish
     dependencies:
       - build
