# nfpm example config file
#
# check https://nfpm.goreleaser.com/configuration for detailed usage
#
name: "br"
arch: "amd64"
platform: "linux"
version: "VERSION"
section: "default"
priority: "extra"
maintainer: "Moritz Poldrack <moritz at poldrack dot dev>"
description: |
  Standalone implementation of rangers bulkrename
vendor: "Moritz Poldracl"
homepage: "https://moritz.sh/code/projects/bulkrenamer/"
license: "BSD2"
files:
  ./pkg/usr/local/bin/br: "/usr/local/bin/br"
  ./pkg/usr/share/man/man1/br.1.gz: "/usr/share/man/man1/br.1.gz"
